require('dotenv').config({ path: './apps/api/.env.production' });

module.exports = {
  apps: [
    {
      name: 'meta-chat-api',
      script: 'apps/api/dist/server.js',
      cwd: '/home/deploy/meta-chat-platform',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        DATABASE_URL: process.env.DATABASE_URL || 'postgresql://metachat:QDpBLzzgyRbp_tU*^-RM6%GcctYoCFKe@localhost:5432/metachat?schema=public',
        REDIS_URL: process.env.REDIS_URL || 'redis://localhost:6379/0',
        RABBITMQ_URL: process.env.RABBITMQ_URL || 'amqp://metachat:vxY%25prw5pBLEAL%3D%26F%23wqvXHN@localhost:5672',
        ADMIN_JWT_SECRET: process.env.ADMIN_JWT_SECRET || 'D367r7UT+BcitB5rxohtp1zuYIEgUPbXMIF0OL9gePjw5ZjRG14OXFVUs1pOJTQbOOl9qLSGM75Fqu0/M+b8WA==',
        ADMIN_KEY_PEPPER: process.env.ADMIN_KEY_PEPPER || 'bc0a3de5561410209482fd9e04c36b8a45f9f645e7ce5c6ec56a4f9aebbb567c',
        ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || 'dB860O4xb/SRO7iZ6PTJVEZSb49c1zZCXi8vmfIqBr8=',
        API_URL: 'https://chat.genai.hr',
        STORAGE_PATH: './storage',
        LOG_LEVEL: 'info',
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
      kill_timeout: 5000,
    },
    {
      name: 'meta-chat-worker',
      script: 'apps/worker/dist/index.js',
      cwd: '/home/deploy/meta-chat-platform',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: process.env.DATABASE_URL || 'postgresql://metachat:QDpBLzzgyRbp_tU*^-RM6%GcctYoCFKe@localhost:5432/metachat?schema=public',
        RABBITMQ_URL: process.env.RABBITMQ_URL || 'amqp://metachat:vxY%25prw5pBLEAL%3D%26F%23wqvXHN@localhost:5672',
        ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || 'dB860O4xb/SRO7iZ6PTJVEZSb49c1zZCXi8vmfIqBr8=',
        ENABLE_CONFIDENCE_ESCALATION: 'true',
        WORKER_VISIBILITY_TIMEOUT_MS: '300000',
        WORKER_MAX_RETRIES: '3',
        WORKER_PREFETCH: '5',
        LOG_LEVEL: 'info',
      },
      error_file: './logs/worker-error.log',
      out_file: './logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
      kill_timeout: 5000,
    },
  ],
};
