require('dotenv').config({ path: './apps/api/.env.production' });

module.exports = {
  apps: [
    {
      name: 'meta-chat-api',
      script: 'apps/api/dist/server.js',
      cwd: '/home/deploy/meta-chat-platform',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3007,
        DATABASE_URL: process.env.DATABASE_URL,
        REDIS_URL: process.env.REDIS_URL,
        RABBITMQ_URL: process.env.RABBITMQ_URL,
        ADMIN_JWT_SECRET: process.env.ADMIN_JWT_SECRET,
        ADMIN_KEY_PEPPER: process.env.ADMIN_KEY_PEPPER,
        ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
        STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY || "",
        STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY || "",
        STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET || "",
        STRIPE_PRICE_STARTER: process.env.STRIPE_PRICE_STARTER || "",
        STRIPE_PRICE_PRO: process.env.STRIPE_PRICE_PRO || "",
        STRIPE_SUCCESS_URL: process.env.STRIPE_SUCCESS_URL || "https://chat.genai.hr/billing/success",
        STRIPE_CANCEL_URL: process.env.STRIPE_CANCEL_URL || "https://chat.genai.hr/billing",
        SMTP_HOST: process.env.SMTP_HOST || "localhost",
        SMTP_PORT: process.env.SMTP_PORT || "587",
        SMTP_SECURE: process.env.SMTP_SECURE || "false",
        SMTP_USER: process.env.SMTP_USER || "",
        SMTP_PASS: process.env.SMTP_PASS || "",
        FROM_EMAIL: process.env.FROM_EMAIL || "noreply@meta-chat-platform.com",
        BASE_URL: process.env.BASE_URL || "https://chat.genai.hr",
        API_CORS_ORIGINS: process.env.API_CORS_ORIGINS || 'https://chat.genai.hr',
        API_URL: 'https://chat.genai.hr',
        STORAGE_PATH: './storage',
        LOG_LEVEL: 'info',
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
      kill_timeout: 5000,
    },
    {
      name: 'meta-chat-worker',
      script: 'apps/worker/dist/index.js',
      cwd: '/home/deploy/meta-chat-platform',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: process.env.DATABASE_URL,
        RABBITMQ_URL: process.env.RABBITMQ_URL,
        ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
        ENABLE_CONFIDENCE_ESCALATION: 'true',
        WORKER_VISIBILITY_TIMEOUT_MS: '300000',
        WORKER_MAX_RETRIES: '3',
        WORKER_PREFETCH: '5',
        LOG_LEVEL: 'info',
      },
      error_file: './logs/worker-error.log',
      out_file: './logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
      kill_timeout: 5000,
    },
  ],
};
